files:
- .github/workflows/build_wheels_lucit_ubdcc_mgmt.yml
- .github/workflows/build_wheels_lucit_ubdcc_shared_modules.yml
- .github/workflows/gh_release.yml
- container/generic_loader/requirements-lucit_ubdcc_dcn.txt
- container/generic_loader/requirements-lucit_ubdcc_mgmt.txt
- container/generic_loader/requirements-lucit_ubdcc_restapi.txt
- dev/docker/lucit-ubdcc-dcn.sh
- dev/docker/lucit-ubdcc-dcn-latest.sh
- dev/docker/lucit-ubdcc-mgmt.sh
- dev/docker/lucit-ubdcc-mgmt-latest.sh
- dev/docker/lucit-ubdcc-restapi.sh
- dev/docker/lucit-ubdcc-restapi-latest.sh
- packages/lucit-ubdcc-dcn/pyproject.toml
- packages/lucit-ubdcc-dcn/requirements.txt
- packages/lucit-ubdcc-dcn/setup.py
- packages/lucit-ubdcc-mgmt/pyproject.toml
- packages/lucit-ubdcc-mgmt/requirements.txt
- packages/lucit-ubdcc-mgmt/setup.py
- packages/lucit-ubdcc-restapi/pyproject.toml
- packages/lucit-ubdcc-restapi/requirements.txt
- packages/lucit-ubdcc-restapi/setup.py
- packages/lucit-ubdcc-shared-modules/lucit_ubdcc_shared_modules/App.py
- packages/lucit-ubdcc-shared-modules/pyproject.toml
- packages/lucit-ubdcc-shared-modules/setup.py
version: 0.0.85
