[tool.poetry]
name = "lucit-ubdcc-shared-modules"
version = "0.0.36"
description = "LUCIT UBDCC Shared Modules"
authors = ["LUCIT Systems and Development <info@lucit.tech>"]
license = "LSOSL - LUCIT Synergetic Open Source License"
readme = "README.md"
homepage = "https://www.lucit.tech/unicorn-binance-depthcache-cluster.html"
documentation = "https://www.lucit.tech/unicorn-binance-depthcache-cluster.html"
repository = "https://github.com/LUCIT-Systems-and-Development/unicorn-binance-depthcache-cluster"

[tool.poetry.urls]
'Howto' = 'https://www.lucit.tech/unicorn-binance-depthcache-cluster.html#howto'
'Documentation' = 'https://unicorn-binance-depthcache-cluster.docs.lucit.tech'
'Wiki' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-binance-depthcache-cluster/wiki'
'Author' = 'https://www.lucit.tech'
'Changes' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-binance-depthcache-cluster/blob/master/packages/lucit-ubdcc-mgmt/CHANGELOG.md'
'License' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-binance-depthcache-cluster/blob/master/LICENSE'
'Issue Tracker' = 'https://github.com/LUCIT-Systems-and-Development/unicorn-binance-depthcache-cluster/issues'
'Telegram' = 'https://t.me/unicorndevs'
'Chat' = 'https://app.gitter.im/#/room/#unicorn-binance-depthcache-cluster:gitter.im'
'Get Support' = 'https://www.lucit.tech/get-support.html'
'LUCIT Online Shop' = 'https://shop.lucit.services/software/unicorn-depthcache-cluster-for-binance'

[tool.poetry.dependencies]
python = ">=3.12.0"
Cython = "*"
fastapi = "*"
kubernetes = "*"
lucit-licensing-python = ">=1.8.2"
uvicorn = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "wheel", "Cython", "pip"]
build-backend = "setuptools.build_meta"

[tool.poetry.package_data]
"lucit_ubdcc_shared_modules" = ["*.so", "*.dll", "*.pyd"]
